sudo: false

language: php

php:
  - 8.2
  - 8.3

matrix:
  fast_finish: true

before_script:
  - composer selfupdate
  - composer update

script:
  - mkdir -p build/logs
  # Run tests
  - php ./vendor/bin/phpunit --configuration tests/phpunit.xml

