sudo: false

language: php

php:
  - 7.2
  - 7.3
  - 7.4

matrix:
  fast_finish: true

allow_failures:
  - php: nightly

before_script:
  - composer selfupdate
  - composer update

script:
  - mkdir -p build/logs
  # Run tests
  - php ./vendor/bin/phpunit --configuration tests/phpunit.xml

after_script:
  - php vendor/bin/coveralls -v
