<?php if($this->aErrorMessages): ?>
<div class="alert alert-danger" role="alert">
	<button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
	<?php foreach($this->aErrorMessages as $sError): ?>
		<?= $sError ?><br />
	<?php endforeach ?>
</div>
<?php endif ?>


<?php
/** @var \SmallUser\Form\Login $form */
$form = $this->loginForm;
$form->prepare();
$form->setAttribute('method', 'post');
?>

<?= $this->form()->openTag($form) ?>
<?php foreach ($form as $element): ?>
	<?php
	/** @var \Zend\Form\Element $element */
	if($element->getAttribute('type') == 'hidden'): ?>
		<?= $this->formInput($element) . $this->formElementErrors($element) ?>
		<?php
		continue;
	endif;
	?>
	<div class="form-group">
		<?php if (!$element instanceof Zend\Form\Element\Button): ?>
			<label><?= $this->formLabel($element) ?></label>
		<?php endif ?>
		<?php if ($element instanceof Zend\Form\Element\Button): ?>
			<?= $this->formButton($element) ?>
		<?php elseif ($element instanceof Zend\Form\Element\Captcha): ?>
			<?= $this->formCaptcha($element) . $this->formElementErrors($element) ?>
		<?php elseif ($element instanceof DoctrineModule\Form\Element\ObjectSelect): ?>
			<?= $this->formSelect($element) . $this->formElementErrors($element) ?>
		<?php elseif ($element instanceof Zend\Form\Element\Textarea): ?>
			<?= $this->formTextarea($element) . $this->formElementErrors($element) ?>
		<?php else: ?>
			<?= $this->formInput($element) . $this->formElementErrors($element) ?>
		<?php endif ?>
	</div>
<?php endforeach ?>
<?php if ($this->redirect): ?>
	<input type="hidden" name="redirect" value="<?= $this->escapeHtml($this->redirect) ?>" />
<?php endif ?>
<?= $this->form()->closeTag() ?>